server:
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schooldb
    username: root
    password: Garfield#1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "Schoolmgt"
    description: "Spring Microservices Project"
    version: "1.0.0"